name: Welcome to the party (second)
on: 
  workflow_dispatch:
jobs:
  say_hello:
    name: "Lets greet the user"
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello there"
      - uses: actions/checkout@v3
      - run: cat .github/workflows/list.txt
        name: display contents of list.txt
      - run: echo "i am step 4"