name: EJ 2

on:
  workflow_dispatch:

jobs:
  fichero:
    runs-on: ubuntu-latest
    steps:
    - name: fichero
      run: echo "creando un fichero" >> hola.txt
      with:
        name: datos
        path: info.txt
  imprimefichero:
    runs-on: ubuntu-latest
    needs: fichero
    steps:
    - uses actions/download-artifact@v4
      with:
        name: datos
    - name: imprimefichero
      run: cat hola.txt