name: Welcome to the party(third)
on: 
  workflow_dispatch:
    inputs:
      thename:
        description: "What is your name?"
        required: false
jobs:
  say_hello:
    name: "Lets greet the user"
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello there ${{ inputs.thename }}"